### ISSUE TITLE
assert(EUR(100.0001) == EUR(100.00009)); // wtf?!

### ISSUE THREAD

**Issue by denizzzka** [qznc/d-money#3]
Hi! 

Sorry for my stupid question, but I can't understand what means:

``` d
assert(EUR(100.0001) == EUR(100.00009));
```

As I understand, IRL 100.0001 Euros isn't equal 100.00009 Euros - this is different amounts. And, for example, if I will use this lib for counting of total after some bank/stock exchange transaction this behaviour can't help me to find calculation errors.

**Comment by qznc** [comment]
By default, the library uses 4 significant digits and rounds to nearest, so 100.00009 gets rounded to 100.0001. If you need higher precision, you can use more significant digits, e.g. `currency!("EUR", 6);`. However, this limits the maximum amount you can use.

If you don't want rounding at all, use `currency!("EUR", 4, roundingMode.UNNECESSARY);`, which throws an exception instead of rounding.

**Comment by denizzzka** [comment]
Thanks for explanation!
